name: pulsar
description: Pulsar Talent Agency

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # splash screen
  flutter_native_splash: ^2.0.2

  # network
  http:
  dio: ^4.0.6
  connectivity_plus: ^2.2.0

  # Google
  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.3
  google_sign_in: ^5.4.2
  cloud_firestore: ^3.1.4
  firebase_storage: ^10.2.3
  google_mobile_ads: ^1.0.1

  flutter_facebook_auth: ^5.0.6

  # storage
  shared_preferences:
  sqflite:
  hive: ^2.0.5

  # files
  path: ^1.8.0
  path_provider:
  file_manager: ^1.0.0

  # video
  video_player: ^2.4.7
  video_compress: ^3.1.1
  flutter_video_info: ^1.2.0
  video_thumbnail: ^0.5.3
  # video_trimmer: ^1.0.0
  ffmpeg_kit_flutter: ^5.1.0

  # image
  cached_network_image: ^3.2.1
  image_picker: ^0.8.4+4
  image: ^3.1.0
  image_cropper: ^2.0.3
  flutter_svg: ^1.0.3

  # performance
  json_serializable:
  json_annotation:
  provider: ^6.0.0
  device_preview: ^1.1.0

  share_plus: ^3.0.4
  permission_handler: ^8.1.4+2
  url_launcher: ^6.1.7
  webview_flutter: ^3.0.4

  # audio
  flutter_sound: ^9.2.13
  audio_session: ^0.1.8

  # text
  extended_text_field: ^10.0.0
  extended_text: ^9.0.0
  flutter_social_textfield: ^0.1.0
  detectable_text_field: ^2.0.3

  # widgets
  pin_code_fields: ^7.1.0
  carousel_slider: ^4.0.0
  animations: ^2.0.3
  extended_nested_scroll_view: ^5.1.3
  camera: ^0.10.0+4
  flutter_spinkit: ^5.0.0
  custom_refresh_indicator: ^1.0.0
  fluttertoast: ^8.0.8
  visibility_detector: ^0.3.3
  # camera_web: ^0.3.0
  firebase_messaging: ^11.2.7
  firebase_messaging_web: ^2.2.8
  advance_pdf_viewer: ^2.0.1
  firebase_crashlytics: ^2.9.0
  firebase_performance: ^0.8.3+3
  # pusher_beams_web: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  build_runner:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/intro/
    - assets/illustrations/
    - assets/categories/
    - assets/documents/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Champagne
      fonts:
        - asset: fonts/cac_champagne.ttf
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: icomoon16
      fonts:
        - asset: fonts/icomoon16.ttf
    - family: icomoon12
      fonts:
        - asset: fonts/icomoon12.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
