name: pulsar
description: Pulsar Talent Agency

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # splash screen
  flutter_native_splash: ^2.0.2

  # network
  http:
  http_parser: ^4.0.2
  dio: ^5.1.2
  connectivity_plus: ^4.0.0

  # Google
  firebase_core: ^2.12.0
  firebase_analytics: ^10.4.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.0
  google_mobile_ads: ^3.0.0

  flutter_facebook_auth: ^5.0.11

  # storage
  shared_preferences:
  sqflite:
  hive: ^2.2.3

  # files
  path: ^1.8.3
  path_provider:
  file_manager: ^1.0.2

  # video
  video_player: ^2.6.1
  video_compress: ^3.1.2
  flutter_video_info: ^1.3.1
  video_thumbnail: ^0.5.3
  # video_trimmer: ^1.0.0
  ffmpeg_kit_flutter: ^5.1.0

  # image
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+5
  image: ^4.0.17
  image_cropper: ^3.0.3
  flutter_svg: ^2.0.5

  # performance
  json_serializable:
  json_annotation:
  provider: ^6.0.5
  device_preview: ^1.1.0
  basic_utils: ^5.5.4

  share_plus: ^7.0.0
  permission_handler: ^10.2.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.0

  # audio
  flutter_sound: ^9.2.13
  audio_session: ^0.1.13

  # text
  extended_text_field: ^11.0.1
  extended_text: ^10.0.1
  flutter_social_textfield: ^0.1.2
  detectable_text_field: ^2.1.0

  # widgets
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.2.1
  animations: ^2.0.7
  extended_nested_scroll_view: ^6.1.0
  camera: ^0.10.5
  flutter_spinkit: ^5.2.0
  custom_refresh_indicator: ^2.0.1
  fluttertoast: ^8.2.1
  visibility_detector: ^0.3.3
  # camera_web: ^0.3.0
  firebase_messaging: ^14.6.0
  firebase_messaging_web: ^3.5.0
  share_plus_web: ^3.1.0
  connectivity_plus_web: ^1.2.5
  # pusher_beams_web: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner:
  flutter_test:
    sdk: flutter
  arb_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/intro/
    - assets/illustrations/
    - assets/categories/
    - assets/documents/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Champagne
      fonts:
        - asset: fonts/cac_champagne.ttf
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: icomoon16
      fonts:
        - asset: fonts/icomoon16.ttf
    - family: icomoon12
      fonts:
        - asset: fonts/icomoon12.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

arb_generator:
  input_filepath: "assets/localizations.csv"
  output_directory: "lib/l10n"
  filename_prepend: "app_"
  csv_settings:
    delimiter: ","
    base_index: 1
