// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4_GE-3BDHk962PhW7ObAeSnnaizg1_Bw',
    appId: '1:62932810627:web:18ce81272b449878a8d4b6',
    messagingSenderId: '62932810627',
    projectId: 'pulsarinc-dev',
    authDomain: 'pulsarinc-dev.firebaseapp.com',
    storageBucket: 'pulsarinc-dev.appspot.com',
    measurementId: 'G-4WBYB007WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Jld267wCVlVcyichL_4mb9DTda4CH30',
    appId: '1:62932810627:android:a1ccda753f4932e0a8d4b6',
    messagingSenderId: '62932810627',
    projectId: 'pulsarinc-dev',
    storageBucket: 'pulsarinc-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjuhyLJ1-KqC_EskW24XQJS-LmpEvhzDs',
    appId: '1:62932810627:ios:78f4183d24e0cc64a8d4b6',
    messagingSenderId: '62932810627',
    projectId: 'pulsarinc-dev',
    storageBucket: 'pulsarinc-dev.appspot.com',
    androidClientId: '62932810627-c53reqk25fjftajh1gcuqcmisshp352v.apps.googleusercontent.com',
    iosClientId: '62932810627-rvkqim1kiq03lrlqtku7c8uca5r9r4et.apps.googleusercontent.com',
    iosBundleId: 'com.pulsar.pulsar',
  );
}
